name: Cordova Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cordova-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Cordova dependencies
        run: cd cordova && npm install

      - name: Build with Cordova
        run: npm run build-cordova
