name: Cordova Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cordova-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/checkout@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build with Cordova
        run: npm run build-cordova
