name: Cordova Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cordova-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: npm install

      - name: Install Cordova globally
        run: npm install -g cordova
  
      - name: Install cordova dependencies
        working-directory: cordova
        run: npm install
  
      - name: Add Android platform
        working-directory: cordova
        run: cordova platform add android
  
      - name: Add Browser platform
        working-directory: cordova
        run: cordova platform add browser

      - name: Build with Cordova
        run: npm run build-cordova

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sombia-Android
          path: cordova/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 90
          overwrite: true
